controllers:
    resource: ../src/Controller/
    type: annotation

# Homepage redirect to notes
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'note_index'
        permanent: true